name: "Publish image"

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: circleci/golang:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build and push Docker image
        run: |
          docker build --build-arg version=`git describe --tags` --build-arg gitCommit=`git rev-parse HEAD` -t drandorg/go-drand:latest .
          echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push drandorg/go-drand:latest
        env:
          DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}