name: "Publish tagged image"

on:
  release:
    types:
      - created
    tags:
      - "v[0-9]+(\\.[0-9]+)*"

jobs:
  tagged-deploy:
    runs-on: ubuntu-latest
    container:
      image: circleci/golang:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build and push tagged Docker image
        run: |
          docker build --build-arg version=`git describe --tags` --build-arg gitCommit=`git rev-parse HEAD` -t drandorg/go-drand:`git describe --tags` .
          echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push drandorg/go-drand:`git describe --tags`
        env:
          DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}