name: "Build/Tests"
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Install Protoc
        run: |
          PROTOC_ZIP=protoc-3.14.0-linux-x86_64.zip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
      - name: Install Go Packages
        run: go get -v -t -d ./...
      - name: Build
        run: |
          make drand
          make drand-client
          make drand-relay-http
          make drand-relay-gossip
          make drand-relay-s3

  tests:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: go get -v -t -d ./...
      - name: ModTidy check
        run: make check-modtidy
      - name: Lint check
        run: |
          make install_lint
          make lint
      - name: Unit tests
        run: make test-unit
      - name: Unit tests
        run: make test-unit
      - name: Integration tests
        run: make test-integration

  coverage:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: make coverage
      - run: bash <(curl -s https://codecov.io/bash)