name: "Build/Tests"
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: go get -v -t -d ./...
      - name: Unit tests
        run: make test-unit
      - run: make test-integration

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: go get -u github.com/ory/go-acc
      - run: go get -v -t -d ./...
      - run: go-acc ./...
      - run: bash <(curl -s https://codecov.io/bash)