name: "Build/Tests"
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.14.0'
      - name: Build
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make drand
          make drand-client
          make drand-relay-http
          make drand-relay-gossip
          make drand-relay-s3

  tests:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.14.0'
      - name: Generate Protobufs
        run: make build_proto
      - name: Modtidy check
        run: make check-modtidy
      - name: Lint check
        run: |
          make install_lint
          make lint
      - name: Unit tests
        run: make test-unit
      - name: Unit tests
        run: make test-unit
      - name: Integration tests
        run: make test-integration

  coverage:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.14.0'
      - run: make coverage
      - run: bash <(curl -s https://codecov.io/bash)