on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: circleci/golang:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: go get -v -t -d ./...
      - run: go get github.com/jstemmer/go-junit-report
      - name: Unit tests
        run: |
          mkdir /tmp/test-results
          trap "go-junit-report </tmp/test-results/go-test.out > /tmp/test-results/go-test-report.xml" EXIT
          make test-unit | tee /tmp/test-results/go-test.out
      - run: make test-integration

  coverage:
    runs-on: ubuntu-latest
    container:
      image: circleci/golang:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: go get -u github.com/ory/go-acc
      - run: go get -v -t -d ./...
      - run: go-acc ./...
      - run: bash <(curl -s https://codecov.io/bash)